/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_ATTR_DELETE( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_attr_delete__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_attr_delete( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_attr_delete_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_ATTR_DELETE = PMPI_ATTR_DELETE
#pragma weak mpi_attr_delete__ = PMPI_ATTR_DELETE
#pragma weak mpi_attr_delete_ = PMPI_ATTR_DELETE
#pragma weak mpi_attr_delete = PMPI_ATTR_DELETE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_ATTR_DELETE = pmpi_attr_delete__
#pragma weak mpi_attr_delete__ = pmpi_attr_delete__
#pragma weak mpi_attr_delete_ = pmpi_attr_delete__
#pragma weak mpi_attr_delete = pmpi_attr_delete__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_ATTR_DELETE = pmpi_attr_delete_
#pragma weak mpi_attr_delete__ = pmpi_attr_delete_
#pragma weak mpi_attr_delete_ = pmpi_attr_delete_
#pragma weak mpi_attr_delete = pmpi_attr_delete_
#else
#pragma weak MPI_ATTR_DELETE = pmpi_attr_delete
#pragma weak mpi_attr_delete__ = pmpi_attr_delete
#pragma weak mpi_attr_delete_ = pmpi_attr_delete
#pragma weak mpi_attr_delete = pmpi_attr_delete
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_ATTR_DELETE( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPI_ATTR_DELETE = PMPI_ATTR_DELETE
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_attr_delete__( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_attr_delete__ = pmpi_attr_delete__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_attr_delete( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_attr_delete = pmpi_attr_delete
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_attr_delete_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_attr_delete_ = pmpi_attr_delete_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_ATTR_DELETE  MPI_ATTR_DELETE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_attr_delete__  mpi_attr_delete__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_attr_delete  mpi_attr_delete
#else
#pragma _HP_SECONDARY_DEF pmpi_attr_delete_  mpi_attr_delete_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_ATTR_DELETE as PMPI_ATTR_DELETE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_attr_delete__ as pmpi_attr_delete__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_attr_delete as pmpi_attr_delete
#else
#pragma _CRI duplicate mpi_attr_delete_ as pmpi_attr_delete_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPI_ATTR_DELETE( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_attr_delete__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_attr_delete( MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_attr_delete_( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_attr_delete__ = MPI_ATTR_DELETE
#pragma weak mpi_attr_delete_ = MPI_ATTR_DELETE
#pragma weak mpi_attr_delete = MPI_ATTR_DELETE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_ATTR_DELETE = mpi_attr_delete__
#pragma weak mpi_attr_delete_ = mpi_attr_delete__
#pragma weak mpi_attr_delete = mpi_attr_delete__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_ATTR_DELETE = mpi_attr_delete_
#pragma weak mpi_attr_delete__ = mpi_attr_delete_
#pragma weak mpi_attr_delete = mpi_attr_delete_
#else
#pragma weak MPI_ATTR_DELETE = mpi_attr_delete
#pragma weak mpi_attr_delete__ = mpi_attr_delete
#pragma weak mpi_attr_delete_ = mpi_attr_delete
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_ATTR_DELETE( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_attr_delete__( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_attr_delete_( MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_attr_delete( MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_attr_delete__ = PMPI_ATTR_DELETE
#pragma weak pmpi_attr_delete_ = PMPI_ATTR_DELETE
#pragma weak pmpi_attr_delete = PMPI_ATTR_DELETE
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_ATTR_DELETE = pmpi_attr_delete__
#pragma weak pmpi_attr_delete_ = pmpi_attr_delete__
#pragma weak pmpi_attr_delete = pmpi_attr_delete__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_ATTR_DELETE = pmpi_attr_delete_
#pragma weak pmpi_attr_delete__ = pmpi_attr_delete_
#pragma weak pmpi_attr_delete = pmpi_attr_delete_
#else
#pragma weak PMPI_ATTR_DELETE = pmpi_attr_delete
#pragma weak pmpi_attr_delete__ = pmpi_attr_delete
#pragma weak pmpi_attr_delete_ = pmpi_attr_delete
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpi_attr_delete_ PMPI_ATTR_DELETE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_attr_delete_ pmpi_attr_delete__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_attr_delete_ pmpi_attr_delete
#else
#define mpi_attr_delete_ pmpi_attr_delete_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings,
   such as those put in place by the globus device when it is building on
   top of a vendor MPI. */
#undef MPI_Attr_delete
#define MPI_Attr_delete PMPI_Attr_delete 

#else

#ifdef F77_NAME_UPPER
#define mpi_attr_delete_ MPI_ATTR_DELETE
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_attr_delete_ mpi_attr_delete__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_attr_delete_ mpi_attr_delete
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_attr_delete_ ( MPI_Fint *v1, MPI_Fint *v2, MPI_Fint *ierr ){
    *ierr = MPI_Attr_delete( (MPI_Comm)(*v1), *v2 );
}
