/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_FILE_READ( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_file_read__( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_file_read( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_file_read_( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_FILE_READ = PMPI_FILE_READ
#pragma weak mpi_file_read__ = PMPI_FILE_READ
#pragma weak mpi_file_read_ = PMPI_FILE_READ
#pragma weak mpi_file_read = PMPI_FILE_READ
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_FILE_READ = pmpi_file_read__
#pragma weak mpi_file_read__ = pmpi_file_read__
#pragma weak mpi_file_read_ = pmpi_file_read__
#pragma weak mpi_file_read = pmpi_file_read__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_FILE_READ = pmpi_file_read_
#pragma weak mpi_file_read__ = pmpi_file_read_
#pragma weak mpi_file_read_ = pmpi_file_read_
#pragma weak mpi_file_read = pmpi_file_read_
#else
#pragma weak MPI_FILE_READ = pmpi_file_read
#pragma weak mpi_file_read__ = pmpi_file_read
#pragma weak mpi_file_read_ = pmpi_file_read
#pragma weak mpi_file_read = pmpi_file_read
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_FILE_READ( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPI_FILE_READ = PMPI_FILE_READ
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_file_read__( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_file_read__ = pmpi_file_read__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_file_read( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_file_read = pmpi_file_read
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_file_read_( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_file_read_ = pmpi_file_read_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_FILE_READ  MPI_FILE_READ
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_file_read__  mpi_file_read__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_file_read  mpi_file_read
#else
#pragma _HP_SECONDARY_DEF pmpi_file_read_  mpi_file_read_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_FILE_READ as PMPI_FILE_READ
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_file_read__ as pmpi_file_read__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_file_read as pmpi_file_read
#else
#pragma _CRI duplicate mpi_file_read_ as pmpi_file_read_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPI_FILE_READ( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_file_read__( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_file_read( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_file_read_( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_file_read__ = MPI_FILE_READ
#pragma weak mpi_file_read_ = MPI_FILE_READ
#pragma weak mpi_file_read = MPI_FILE_READ
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_FILE_READ = mpi_file_read__
#pragma weak mpi_file_read_ = mpi_file_read__
#pragma weak mpi_file_read = mpi_file_read__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_FILE_READ = mpi_file_read_
#pragma weak mpi_file_read__ = mpi_file_read_
#pragma weak mpi_file_read = mpi_file_read_
#else
#pragma weak MPI_FILE_READ = mpi_file_read
#pragma weak mpi_file_read__ = mpi_file_read
#pragma weak mpi_file_read_ = mpi_file_read
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_FILE_READ( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_file_read__( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_file_read_( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_file_read( MPI_Fint *, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_file_read__ = PMPI_FILE_READ
#pragma weak pmpi_file_read_ = PMPI_FILE_READ
#pragma weak pmpi_file_read = PMPI_FILE_READ
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_FILE_READ = pmpi_file_read__
#pragma weak pmpi_file_read_ = pmpi_file_read__
#pragma weak pmpi_file_read = pmpi_file_read__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_FILE_READ = pmpi_file_read_
#pragma weak pmpi_file_read__ = pmpi_file_read_
#pragma weak pmpi_file_read = pmpi_file_read_
#else
#pragma weak PMPI_FILE_READ = pmpi_file_read
#pragma weak pmpi_file_read__ = pmpi_file_read
#pragma weak pmpi_file_read_ = pmpi_file_read
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpi_file_read_ PMPI_FILE_READ
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_file_read_ pmpi_file_read__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_file_read_ pmpi_file_read
#else
#define mpi_file_read_ pmpi_file_read_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings,
   such as those put in place by the globus device when it is building on
   top of a vendor MPI. */
#undef MPI_File_read
#define MPI_File_read PMPI_File_read 

#else

#ifdef F77_NAME_UPPER
#define mpi_file_read_ MPI_FILE_READ
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_file_read_ mpi_file_read__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_file_read_ mpi_file_read
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_file_read_ ( MPI_Fint *v1, void*v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *ierr ){
#ifdef MPI_MODE_RDONLY
    *ierr = MPI_File_read( MPI_File_f2c(*v1), v2, *v3, (MPI_Datatype)(*v4), (MPI_Status *)(v5) );
#else
*ierr = MPI_ERR_INTERN;
#endif
}
