/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_GET_ADDRESS( void*, MPI_Aint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_get_address__( void*, MPI_Aint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_get_address( void*, MPI_Aint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_get_address_( void*, MPI_Aint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_GET_ADDRESS = PMPI_GET_ADDRESS
#pragma weak mpi_get_address__ = PMPI_GET_ADDRESS
#pragma weak mpi_get_address_ = PMPI_GET_ADDRESS
#pragma weak mpi_get_address = PMPI_GET_ADDRESS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_GET_ADDRESS = pmpi_get_address__
#pragma weak mpi_get_address__ = pmpi_get_address__
#pragma weak mpi_get_address_ = pmpi_get_address__
#pragma weak mpi_get_address = pmpi_get_address__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_GET_ADDRESS = pmpi_get_address_
#pragma weak mpi_get_address__ = pmpi_get_address_
#pragma weak mpi_get_address_ = pmpi_get_address_
#pragma weak mpi_get_address = pmpi_get_address_
#else
#pragma weak MPI_GET_ADDRESS = pmpi_get_address
#pragma weak mpi_get_address__ = pmpi_get_address
#pragma weak mpi_get_address_ = pmpi_get_address
#pragma weak mpi_get_address = pmpi_get_address
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_GET_ADDRESS( void*, MPI_Aint *, MPI_Fint * );

#pragma weak MPI_GET_ADDRESS = PMPI_GET_ADDRESS
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_get_address__( void*, MPI_Aint *, MPI_Fint * );

#pragma weak mpi_get_address__ = pmpi_get_address__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_get_address( void*, MPI_Aint *, MPI_Fint * );

#pragma weak mpi_get_address = pmpi_get_address
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_get_address_( void*, MPI_Aint *, MPI_Fint * );

#pragma weak mpi_get_address_ = pmpi_get_address_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_GET_ADDRESS  MPI_GET_ADDRESS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_get_address__  mpi_get_address__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_get_address  mpi_get_address
#else
#pragma _HP_SECONDARY_DEF pmpi_get_address_  mpi_get_address_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_GET_ADDRESS as PMPI_GET_ADDRESS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_get_address__ as pmpi_get_address__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_get_address as pmpi_get_address
#else
#pragma _CRI duplicate mpi_get_address_ as pmpi_get_address_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPI_GET_ADDRESS( void*, MPI_Aint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_get_address__( void*, MPI_Aint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_get_address( void*, MPI_Aint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_get_address_( void*, MPI_Aint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_get_address__ = MPI_GET_ADDRESS
#pragma weak mpi_get_address_ = MPI_GET_ADDRESS
#pragma weak mpi_get_address = MPI_GET_ADDRESS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_GET_ADDRESS = mpi_get_address__
#pragma weak mpi_get_address_ = mpi_get_address__
#pragma weak mpi_get_address = mpi_get_address__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_GET_ADDRESS = mpi_get_address_
#pragma weak mpi_get_address__ = mpi_get_address_
#pragma weak mpi_get_address = mpi_get_address_
#else
#pragma weak MPI_GET_ADDRESS = mpi_get_address
#pragma weak mpi_get_address__ = mpi_get_address
#pragma weak mpi_get_address_ = mpi_get_address
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_GET_ADDRESS( void*, MPI_Aint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_get_address__( void*, MPI_Aint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_get_address_( void*, MPI_Aint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_get_address( void*, MPI_Aint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_get_address__ = PMPI_GET_ADDRESS
#pragma weak pmpi_get_address_ = PMPI_GET_ADDRESS
#pragma weak pmpi_get_address = PMPI_GET_ADDRESS
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_GET_ADDRESS = pmpi_get_address__
#pragma weak pmpi_get_address_ = pmpi_get_address__
#pragma weak pmpi_get_address = pmpi_get_address__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_GET_ADDRESS = pmpi_get_address_
#pragma weak pmpi_get_address__ = pmpi_get_address_
#pragma weak pmpi_get_address = pmpi_get_address_
#else
#pragma weak PMPI_GET_ADDRESS = pmpi_get_address
#pragma weak pmpi_get_address__ = pmpi_get_address
#pragma weak pmpi_get_address_ = pmpi_get_address
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpi_get_address_ PMPI_GET_ADDRESS
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_get_address_ pmpi_get_address__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_get_address_ pmpi_get_address
#else
#define mpi_get_address_ pmpi_get_address_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings,
   such as those put in place by the globus device when it is building on
   top of a vendor MPI. */
#undef MPI_Get_address
#define MPI_Get_address PMPI_Get_address 

#else

#ifdef F77_NAME_UPPER
#define mpi_get_address_ MPI_GET_ADDRESS
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_get_address_ mpi_get_address__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_get_address_ mpi_get_address
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
#include "mpierrs.h"
#include <stdio.h>
#include "mpierror.h"
FORT_DLL_SPEC void FORT_CALL mpi_get_address_ ( void*v1, MPI_Aint *v2, MPI_Fint *ierr ){
    MPI_Aint a;
    *ierr = MPI_Get_address( v1, &a );

#ifndef USE_POINTER_FOR_BOTTOM
    a = a - (MPIR_Pint) MPIR_F_MPI_BOTTOM;
#endif
    *v2 =  a;
}
