/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


/* Begin MPI profiling block */
#if defined(USE_WEAK_SYMBOLS) && !defined(USE_ONLY_MPI_NAMES) 
#if defined(HAVE_MULTIPLE_PRAGMA_WEAK)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_SCATTER_BLOCK( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_scatter_block__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_scatter_block( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_scatter_block_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak MPI_REDUCE_SCATTER_BLOCK = PMPI_REDUCE_SCATTER_BLOCK
#pragma weak mpi_reduce_scatter_block__ = PMPI_REDUCE_SCATTER_BLOCK
#pragma weak mpi_reduce_scatter_block_ = PMPI_REDUCE_SCATTER_BLOCK
#pragma weak mpi_reduce_scatter_block = PMPI_REDUCE_SCATTER_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_REDUCE_SCATTER_BLOCK = pmpi_reduce_scatter_block__
#pragma weak mpi_reduce_scatter_block__ = pmpi_reduce_scatter_block__
#pragma weak mpi_reduce_scatter_block_ = pmpi_reduce_scatter_block__
#pragma weak mpi_reduce_scatter_block = pmpi_reduce_scatter_block__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_REDUCE_SCATTER_BLOCK = pmpi_reduce_scatter_block_
#pragma weak mpi_reduce_scatter_block__ = pmpi_reduce_scatter_block_
#pragma weak mpi_reduce_scatter_block_ = pmpi_reduce_scatter_block_
#pragma weak mpi_reduce_scatter_block = pmpi_reduce_scatter_block_
#else
#pragma weak MPI_REDUCE_SCATTER_BLOCK = pmpi_reduce_scatter_block
#pragma weak mpi_reduce_scatter_block__ = pmpi_reduce_scatter_block
#pragma weak mpi_reduce_scatter_block_ = pmpi_reduce_scatter_block
#pragma weak mpi_reduce_scatter_block = pmpi_reduce_scatter_block
#endif



#elif defined(HAVE_PRAGMA_WEAK)

#if defined(F77_NAME_UPPER)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_SCATTER_BLOCK( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak MPI_REDUCE_SCATTER_BLOCK = PMPI_REDUCE_SCATTER_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_scatter_block__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_reduce_scatter_block__ = pmpi_reduce_scatter_block__
#elif !defined(F77_NAME_LOWER_USCORE)
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_scatter_block( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_reduce_scatter_block = pmpi_reduce_scatter_block
#else
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_scatter_block_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#pragma weak mpi_reduce_scatter_block_ = pmpi_reduce_scatter_block_
#endif

#elif defined(HAVE_PRAGMA_HP_SEC_DEF)
#if defined(F77_NAME_UPPER)
#pragma _HP_SECONDARY_DEF PMPI_REDUCE_SCATTER_BLOCK  MPI_REDUCE_SCATTER_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _HP_SECONDARY_DEF pmpi_reduce_scatter_block__  mpi_reduce_scatter_block__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _HP_SECONDARY_DEF pmpi_reduce_scatter_block  mpi_reduce_scatter_block
#else
#pragma _HP_SECONDARY_DEF pmpi_reduce_scatter_block_  mpi_reduce_scatter_block_
#endif

#elif defined(HAVE_PRAGMA_CRI_DUP)
#if defined(F77_NAME_UPPER)
#pragma _CRI duplicate MPI_REDUCE_SCATTER_BLOCK as PMPI_REDUCE_SCATTER_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma _CRI duplicate mpi_reduce_scatter_block__ as pmpi_reduce_scatter_block__
#elif !defined(F77_NAME_LOWER_USCORE)
#pragma _CRI duplicate mpi_reduce_scatter_block as pmpi_reduce_scatter_block
#else
#pragma _CRI duplicate mpi_reduce_scatter_block_ as pmpi_reduce_scatter_block_
#endif
#endif /* HAVE_PRAGMA_WEAK */
#endif /* USE_WEAK_SYMBOLS */
/* End MPI profiling block */


/* These definitions are used only for generating the Fortran wrappers */
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK) && \
    defined(USE_ONLY_MPI_NAMES)
extern FORT_DLL_SPEC void FORT_CALL MPI_REDUCE_SCATTER_BLOCK( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_scatter_block__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_scatter_block( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
extern FORT_DLL_SPEC void FORT_CALL mpi_reduce_scatter_block_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#if defined(F77_NAME_UPPER)
#pragma weak mpi_reduce_scatter_block__ = MPI_REDUCE_SCATTER_BLOCK
#pragma weak mpi_reduce_scatter_block_ = MPI_REDUCE_SCATTER_BLOCK
#pragma weak mpi_reduce_scatter_block = MPI_REDUCE_SCATTER_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak MPI_REDUCE_SCATTER_BLOCK = mpi_reduce_scatter_block__
#pragma weak mpi_reduce_scatter_block_ = mpi_reduce_scatter_block__
#pragma weak mpi_reduce_scatter_block = mpi_reduce_scatter_block__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak MPI_REDUCE_SCATTER_BLOCK = mpi_reduce_scatter_block_
#pragma weak mpi_reduce_scatter_block__ = mpi_reduce_scatter_block_
#pragma weak mpi_reduce_scatter_block = mpi_reduce_scatter_block_
#else
#pragma weak MPI_REDUCE_SCATTER_BLOCK = mpi_reduce_scatter_block
#pragma weak mpi_reduce_scatter_block__ = mpi_reduce_scatter_block
#pragma weak mpi_reduce_scatter_block_ = mpi_reduce_scatter_block
#endif

#endif

/* Map the name to the correct form */
#ifndef MPICH_MPI_FROM_PMPI
#if defined(USE_WEAK_SYMBOLS) && defined(HAVE_MULTIPLE_PRAGMA_WEAK)
/* Define the weak versions of the PMPI routine*/
#ifndef F77_NAME_UPPER
extern FORT_DLL_SPEC void FORT_CALL PMPI_REDUCE_SCATTER_BLOCK( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_2USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_scatter_block__( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER_USCORE
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_scatter_block_( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );
#endif
#ifndef F77_NAME_LOWER
extern FORT_DLL_SPEC void FORT_CALL pmpi_reduce_scatter_block( void*, void*, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint *, MPI_Fint * );

#endif

#if defined(F77_NAME_UPPER)
#pragma weak pmpi_reduce_scatter_block__ = PMPI_REDUCE_SCATTER_BLOCK
#pragma weak pmpi_reduce_scatter_block_ = PMPI_REDUCE_SCATTER_BLOCK
#pragma weak pmpi_reduce_scatter_block = PMPI_REDUCE_SCATTER_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#pragma weak PMPI_REDUCE_SCATTER_BLOCK = pmpi_reduce_scatter_block__
#pragma weak pmpi_reduce_scatter_block_ = pmpi_reduce_scatter_block__
#pragma weak pmpi_reduce_scatter_block = pmpi_reduce_scatter_block__
#elif defined(F77_NAME_LOWER_USCORE)
#pragma weak PMPI_REDUCE_SCATTER_BLOCK = pmpi_reduce_scatter_block_
#pragma weak pmpi_reduce_scatter_block__ = pmpi_reduce_scatter_block_
#pragma weak pmpi_reduce_scatter_block = pmpi_reduce_scatter_block_
#else
#pragma weak PMPI_REDUCE_SCATTER_BLOCK = pmpi_reduce_scatter_block
#pragma weak pmpi_reduce_scatter_block__ = pmpi_reduce_scatter_block
#pragma weak pmpi_reduce_scatter_block_ = pmpi_reduce_scatter_block
#endif /* Test on name mapping */
#endif /* Use multiple pragma weak */

#ifdef F77_NAME_UPPER
#define mpi_reduce_scatter_block_ PMPI_REDUCE_SCATTER_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_reduce_scatter_block_ pmpi_reduce_scatter_block__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_reduce_scatter_block_ pmpi_reduce_scatter_block
#else
#define mpi_reduce_scatter_block_ pmpi_reduce_scatter_block_
#endif /* Test on name mapping */

/* This defines the routine that we call, which must be the PMPI version
   since we're renaming the Fortran entry as the pmpi version.  The MPI name
   must be undefined first to prevent any conflicts with previous renamings,
   such as those put in place by the globus device when it is building on
   top of a vendor MPI. */
#undef MPI_Reduce_scatter_block
#define MPI_Reduce_scatter_block PMPI_Reduce_scatter_block 

#else

#ifdef F77_NAME_UPPER
#define mpi_reduce_scatter_block_ MPI_REDUCE_SCATTER_BLOCK
#elif defined(F77_NAME_LOWER_2USCORE)
#define mpi_reduce_scatter_block_ mpi_reduce_scatter_block__
#elif !defined(F77_NAME_LOWER_USCORE)
#define mpi_reduce_scatter_block_ mpi_reduce_scatter_block
/* Else leave name alone */
#endif


#endif /* MPICH_MPI_FROM_PMPI */

/* Prototypes for the Fortran interfaces */
#include "fproto.h"
FORT_DLL_SPEC void FORT_CALL mpi_reduce_scatter_block_ ( void*v1, void*v2, MPI_Fint *v3, MPI_Fint *v4, MPI_Fint *v5, MPI_Fint *v6, MPI_Fint *ierr ){
    *ierr = MPI_Reduce_scatter_block( v1, v2, *v3, (MPI_Datatype)(*v4), *v5, (MPI_Comm)(*v6) );
}
